// Journey Configuration - The Design Quest
// Defines all levels and quests for the LFA creation journey

import { Level, Badge, Quest, ComponentType } from "@/types";

// Re-export types for convenience
export type { Level as JourneyLevel, Quest, Badge } from "@/types";

export const BADGES: Record<string, Badge> = {
  PROBLEM_MASTER: {
    id: "problem_master",
    name: "Problem Master",
    description: "Completed problem definition and context analysis",
    icon: "🎯",
    criteria: { type: "completion", threshold: 100 },
  },
  STAKEHOLDER_MASTER: {
    id: "stakeholder_master",
    name: "Stakeholder Master",
    description: "Mapped all stakeholders and their practice changes",
    icon: "👥",
    criteria: { type: "completion", threshold: 100 },
  },
  STRATEGY_ARCHITECT: {
    id: "strategy_architect",
    name: "Strategy Architect",
    description: "Designed comprehensive intervention strategy",
    icon: "🛠️",
    criteria: { type: "completion", threshold: 100 },
  },
  IMPACT_TRACKER: {
    id: "impact_tracker",
    name: "Impact Tracker",
    description: "Created robust M&E framework with indicators",
    icon: "📊",
    criteria: { type: "completion", threshold: 100 },
  },
  DESIGN_MASTER: {
    id: "design_master",
    name: "Design Master",
    description: "Completed full LFA design journey",
    icon: "🏆",
    criteria: { type: "completion", threshold: 100 },
  },
  QUALITY_CHAMPION: {
    id: "quality_champion",
    name: "Quality Champion",
    description: "Achieved logic validation score above 90%",
    icon: "⭐",
    criteria: { type: "quality", threshold: 90 },
  },
  SPEED_DESIGNER: {
    id: "speed_designer",
    name: "Speed Designer",
    description: "Completed LFA design in under 5 days",
    icon: "🚀",
    criteria: { type: "speed", threshold: 5 },
  },
  COLLABORATOR: {
    id: "collaborator",
    name: "Collaborator",
    description: "Shared project with 3+ team members",
    icon: "🤝",
    criteria: { type: "collaboration", threshold: 3 },
  },
};

export const JOURNEY_LEVELS: Level[] = [
  {
    id: 1,
    level: 1,
    name: "Understanding the Landscape",
    title: "Understanding the Landscape",
    subtitle: "Define your problem, context, and vision for change",
    description: "Define your problem, context, and vision for change",
    icon: "🗺️",
    badge: BADGES.PROBLEM_MASTER,
    isUnlocked: true,
    completionPercentage: 0,
    quests: [
      {
        id: "vision",
        levelId: 1,
        questNumber: 1,
        title: "Define Your Vision",
        description: "Define the vision and purpose of your education program",
        icon: "🎯",
        points: 50,
        estimatedMinutes: 15,
        instructions: [
          "Define your program vision statement",
          "Explain why this matters",
          "Identify target beneficiaries",
        ],
        componentType: "PROBLEM_DEFINITION" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
      {
        id: "geography",
        levelId: 1,
        questNumber: 2,
        title: "Define Your Battleground",
        description: "Identify the geographic context where you'll work",
        icon: "🗺️",
        points: 40,
        estimatedMinutes: 10,
        instructions: [
          "Select the state(s) where your program will operate",
          "Choose the districts within those states",
          "Specify the blocks if applicable",
        ],
        componentType: "PROBLEM_DEFINITION" as ComponentType,
        fields: [],
        pointsReward: 40,
        isComplete: false,
      },
      {
        id: "context",
        levelId: 1,
        questNumber: 3,
        title: "Understand the Landscape",
        description: "Analyze the educational landscape and challenges",
        icon: "📊",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "Describe the current state of education",
          "Identify key challenges",
          "Note existing programs and interventions",
        ],
        componentType: "PROBLEM_DEFINITION" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
    ],
  },
  {
    id: 2,
    level: 2,
    name: "Mapping Your Allies",
    title: "Mapping Your Allies",
    subtitle: "Identify stakeholders and their practice changes",
    description: "Identify stakeholders and their practice changes",
    icon: "👥",
    badge: BADGES.STAKEHOLDER_MASTER,
    isUnlocked: false,
    completionPercentage: 0,
    quests: [
      {
        id: "stakeholder-map",
        levelId: 2,
        questNumber: 1,
        title: "Map Your Stakeholders",
        description: "Identify all stakeholders involved in your program",
        icon: "👥",
        points: 60,
        estimatedMinutes: 25,
        instructions: [
          "List all stakeholders who will be involved",
          "Categorize by type and level",
          "Define their role in the program",
        ],
        componentType: "STAKEHOLDER_FRAMEWORK" as ComponentType,
        fields: [],
        pointsReward: 60,
        isComplete: false,
      },
      {
        id: "power-analysis",
        levelId: 2,
        questNumber: 2,
        title: "Power Analysis",
        description: "Analyze stakeholder influence and interest",
        icon: "⚡",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "Map stakeholders by power and interest",
          "Identify key players",
          "Plan engagement strategies",
        ],
        componentType: "STAKEHOLDER_FRAMEWORK" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
      {
        id: "engagement",
        levelId: 2,
        questNumber: 3,
        title: "Engagement Strategy",
        description: "Plan how you will engage with each stakeholder group",
        icon: "🤝",
        points: 50,
        estimatedMinutes: 15,
        instructions: [
          "Define engagement approach for each group",
          "Create communication plan",
          "Set engagement milestones",
        ],
        componentType: "STAKEHOLDER_FRAMEWORK" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
    ],
  },
  {
    id: 3,
    level: 3,
    name: "Charting the Path",
    title: "Charting the Path",
    subtitle: "Design your intervention strategy",
    description: "Design your intervention strategy",
    icon: "🛤️",
    badge: BADGES.STRATEGY_ARCHITECT,
    isUnlocked: false,
    completionPercentage: 0,
    quests: [
      {
        id: "goal",
        levelId: 3,
        questNumber: 1,
        title: "Define Your Goal",
        description: "Define the overall goal your program contributes to",
        icon: "🎯",
        points: 50,
        estimatedMinutes: 15,
        instructions: [
          "Define the long-term impact",
          "Connect to broader development goals",
          "Ensure alignment with stakeholder needs",
        ],
        componentType: "THEORY_OF_CHANGE" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
      {
        id: "outcomes",
        levelId: 3,
        questNumber: 2,
        title: "Design Outcomes",
        description: "Define the outcomes your program will achieve",
        icon: "📈",
        points: 60,
        estimatedMinutes: 25,
        instructions: [
          "Define 2-4 key outcomes",
          "Ensure they are measurable",
          "Link to the overall goal",
        ],
        componentType: "THEORY_OF_CHANGE" as ComponentType,
        fields: [],
        pointsReward: 60,
        isComplete: false,
      },
      {
        id: "outputs",
        levelId: 3,
        questNumber: 3,
        title: "Plan Outputs",
        description: "Define the outputs (deliverables) your program will produce",
        icon: "📦",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "List key outputs for each outcome",
          "Define quantities and specifications",
          "Ensure logical connection to outcomes",
        ],
        componentType: "IMPLEMENTATION_DESIGN" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
      {
        id: "activities",
        levelId: 3,
        questNumber: 4,
        title: "Design Activities",
        description: "Define the activities you will implement",
        icon: "⚙️",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "List activities for each output",
          "Define timelines and responsibilities",
          "Identify resource requirements",
        ],
        componentType: "IMPLEMENTATION_DESIGN" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
    ],
  },
  {
    id: 4,
    level: 4,
    name: "Measuring Victory",
    title: "Measuring Victory",
    subtitle: "Create your monitoring and evaluation framework",
    description: "Create your monitoring and evaluation framework",
    icon: "📊",
    badge: BADGES.IMPACT_TRACKER,
    isUnlocked: false,
    completionPercentage: 0,
    quests: [
      {
        id: "indicators",
        levelId: 4,
        questNumber: 1,
        title: "Define Indicators",
        description: "Create indicators to measure success at each level",
        icon: "📊",
        points: 70,
        estimatedMinutes: 30,
        instructions: [
          "Define indicators for goal, outcomes, and outputs",
          "Ensure SMART criteria",
          "Plan data collection methods",
        ],
        componentType: "MONITORING_EVALUATION" as ComponentType,
        fields: [],
        pointsReward: 70,
        isComplete: false,
      },
      {
        id: "mov",
        levelId: 4,
        questNumber: 2,
        title: "Means of Verification",
        description: "Define how you will collect data for each indicator",
        icon: "📋",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "Identify data sources",
          "Define collection methods",
          "Set collection frequency",
        ],
        componentType: "MONITORING_EVALUATION" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
      {
        id: "risks",
        levelId: 4,
        questNumber: 3,
        title: "Risks & Assumptions",
        description: "Identify assumptions and risks that could affect your program",
        icon: "⚠️",
        points: 50,
        estimatedMinutes: 20,
        instructions: [
          "List key assumptions",
          "Identify potential risks",
          "Plan mitigation strategies",
        ],
        componentType: "MONITORING_EVALUATION" as ComponentType,
        fields: [],
        pointsReward: 50,
        isComplete: false,
      },
    ],
  },
  {
    id: 5,
    level: 5,
    name: "Forging the Blueprint",
    title: "Forging the Blueprint",
    subtitle: "Finalize and export your LFA",
    description: "Finalize and export your LFA",
    icon: "📜",
    badge: BADGES.DESIGN_MASTER,
    isUnlocked: false,
    completionPercentage: 0,
    quests: [
      {
        id: "review",
        levelId: 5,
        questNumber: 1,
        title: "Review Your LFA",
        description: "Review your complete LFA and make final adjustments",
        icon: "✅",
        points: 40,
        estimatedMinutes: 30,
        instructions: [
          "Review all sections for completeness",
          "Check logical consistency",
          "Make final adjustments",
        ],
        componentType: "MONITORING_EVALUATION" as ComponentType,
        fields: [],
        pointsReward: 40,
        isComplete: false,
      },
      {
        id: "export",
        levelId: 5,
        questNumber: 2,
        title: "Export Your Blueprint",
        description: "Export your LFA in various formats for sharing",
        icon: "📄",
        points: 30,
        estimatedMinutes: 10,
        instructions: [
          "Choose export format (PDF, Excel, Word)",
          "Generate professional document",
          "Share with stakeholders",
        ],
        componentType: "MONITORING_EVALUATION" as ComponentType,
        fields: [],
        pointsReward: 30,
        isComplete: false,
      },
    ],
  },
];

// Points configuration
export const POINTS_CONFIG = {
  questCompletion: 10,
  levelCompletion: 50,
  dailyStreak: 5,
  weeklyStreak: 25,
  aiSuggestionApplied: 2,
  qualityBonus: 20,
  badgeEarned: 100,
  streakBonus: {
    3: 10,
    7: 25,
    14: 50,
    30: 100,
  } as Record<number, number>,
};

// Calculate total quest points
export function calculateQuestPoints(quests: Quest[]): number {
  return quests.reduce((sum, q) => sum + (q.points || q.pointsReward || 0), 0);
}

// Get next quest
export function getNextQuest(
  currentLevel: number,
  currentQuest: number
): { level: number; quest: number } | null {
  const level = JOURNEY_LEVELS.find((l) => l.level === currentLevel);
  if (!level) return null;

  if (currentQuest < level.quests.length) {
    return { level: currentLevel, quest: currentQuest + 1 };
  }

  const nextLevel = JOURNEY_LEVELS.find((l) => l.level === currentLevel + 1);
  if (nextLevel) {
    return { level: currentLevel + 1, quest: 1 };
  }

  return null; // Journey complete
}